---
# tasks file for Kubernetes

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Import Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce=17.03.2~ce-0~ubuntu-xenial
    state: present

- name: Hold Docker CE version
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Make sure Docker is stopped
  service:
    name: docker
    state: stopped

- name: Remove node key
  file:
    path: /etc/docker/key.json
    state: absent

- name: Import Google GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Kubernetes binaries
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubernetes-cni
    - kubelet=1.10.0-00
    - kubeadm=1.10.0-00
    - kubectl=1.10.0-00
  notify:
    - Clean APT cache
